export const OPEN_POST_MODEL = "OPEN_POST_MODEL";
export const CLOSE_POST_MODEL = "CLOSE_POST_MODEL";
export const OPEN_PROFILE_MODEL = "OPEN_PROFILE_MODEL";
export const CLOSE_PROFILE_MODEL = "CLOSE_PROFILE_MODEL";
